CC     = g++
OPT    = -O0
DEBUG  = -g
#OTHER  = -Wno-deprecated
#CFLAGS = $(OPT) $(OTHER)
CFLAGS = $(DEBUG) $(OTHER)

MODULE = run
SRCS = and.cpp
OBJS = $(SRCS:.cpp=.o)

all: run.x


include Makefile.defs
