#!/usr/bin/make -f
# COPYRIGHT (C) 2004-2007 Eklectic Ally, Inc. DBA ESLX Inc. -------{{{#
# See ESLX_LICENSE for information on legal usage of this file.   #
# -----------------------------------------------------------------}}}#

#----------------------------------------------------------------------
# Uncomment and replace the following to set the name of the executable;
# otherwise, the name of the directory will be used.
#---
MODULE=datatypes

#----------------------------------------------------------------------
# Uncomment and set the following to specify which files consitute source
# files to be compiled into objects; otherwise, filenames matching *.cpp
# will be used.
#---
SRCS=datatypes.cpp

#----------------------------------------------------------------------
# Default mode (exe => create executable, sim => run the simulation)
#---
#DFLT=sim

include ../../Makefile.rules

# COPYRIGHT (C) 2004-2007 Eklectic Ally, Inc. DBA ESLX Inc.--------{{{#
# See ESLX_LICENSE for information on legal usage of this file.   #
# -----------------------------------------------------------------}}}#
#END $Id$
